### PR TITLE
Use modern APIs to update nameplates

### PR DESCRIPTION
**Pull request by LiangYuxuan**

### CODE REVIEW

**Comment by SwimmingTiger** [comment]
I have a question. Is it really faster to traverse 40 units at a time than the previous method? The previous method only needs to traverse about 20 at a time.
```
function CodexQuest:UpdateAllNameplates()
    for i = 1, 40 do
        local unitID = "nameplate" .. i
        if UnitExists(unitID) then
            CodexQuest:UpdateNameplate(unitID)
        end
    end
end
```

**Comment by SwimmingTiger** [comment]
Also, if it creates `codexIcons` only when it need them, instead of creating and hiding them for each nameplate, would it have better performance?

**Comment by LiangYuxuan** [comment]
UnitExists is called to tell corresponding unit is exists or not. I think it's better to break when a unit is found not exists, then it will be better than the old method. But actually we should update the new-created one when it is created and update all nameplates when quest log is updated.

For the latter one, I think it is.

**Comment by LiangYuxuan** [comment]
Currently, I think the main performance issue is addressed to redrawing all map nodes once quest log is updated, if you have about 10 quests on one map, it will lag about 0.5s every 5s or less.

**Comment by pgarneau** [comment]
Fix the conflict @LiangYuxuan and Ill test it out ingame. Thanks

**Comment by LiangYuxuan** [comment]
@pgarneau conflict resolved :)

**Comment by SwimmingTiger** [comment]
Redrawing has not been as frequent as a few seconds. The current master branch redraws only when the following events occur:
1. Pick up a new quest.
2. Give up a quest.
3. Complete a single goal for a quest.
4. A quest is marked as complete.
5. Turnin a quest.

You can add `print()` to `function CodexMap:UpdateNodes()` to track the redraw situation. I did a similar job while refactoring the rendering pipeline and I have reduced the redraw to an acceptable range. (It usually won't be redrawed once in 5 seconds.)
https://github.com/project-classic/ClassicCodex/blob/master/map.lua#L611

I have this tracking code:
```
print('---------- UpdateNodes', date())
print(debugstack())
```

**Comment by SwimmingTiger** [comment]
However, it seems very easy to just refresh the markers for a single quest, just name the marker by the quest id.

```lua
CodexMap.HBDP:AddWorldMapIconMap(--[["Map"]] tostring(questId), CodexMap.markers[i], worldMapId, x, y, HBD_PINS_WORLDMAP_SHOW_PARENT)
```

**Pull request merged**
