### PR TITLE
Fix performance issues and refactoring the addon with the modern Wow API

### PR DESCRIPTION
**Pull request by SwimmingTiger**
The addon redraws all map markers when a nameplate disappearing or the player entering a new zone, which can cause significant performance issues.

In particular, turning the lens in an area full of nameplates, redrawing events will occur in each rendering ticket.

It seems that registering NAME_PLATE_UNIT_REMOVED and letting it hit the else branch (causing redraw) is an unexpected result. Removing it does not seem to have side effects, but it can significantly alleviate performance issues when turning the lens.

Similarly, since CodexMap:UpdateNodes() draws all map markers each time, it is no longer necessary to register for zone change events.

### CODE REVIEW

**Comment by SwimmingTiger** [comment]
This may fix https://github.com/project-classic/ClassicCodex/issues/31 and https://github.com/project-classic/ClassicCodex/issues/27

For https://github.com/project-classic/ClassicCodex/issues/27, although it takes a long time to draw these markers each time, there may no significant performance issue as long as it is not redrawn.

**Comment by SwimmingTiger** [comment]
If someone wants to try my fix right away, the addon package can be downloaded via the link below.

Must rename the directory to ClassicCodex, or the addon will not load.

https://github.com/SwimmingTiger/ClassicCodex/archive/master.zip

If you find that my changes are causing any problems, please reply here.

**Comment by SwimmingTiger** [comment]
Done. rendering pipeline has been refactored to ensure that it is redraw only when necessary.
I have only conducted a simple test and I will continue to test it in the game to make sure there are no side effects.

**Comment by SwimmingTiger** [comment]
Fixed the problem with the database not matching the real quest name. Because Blizzard API returns the quest id directly, everything becomes very simple.
```
local title, _, _, header, _, complete, _, questId = GetQuestLogTitle(questLogId)
```

**Comment by SwimmingTiger** [comment]
Done the fix. I have modified all the code to get the quest title from the Blizzard API. The addon now only uses the quest titles in its own database.

I have tested and used ClassicCodex's zhTW database in a zhCN Wow client (most quest names don't match). It seems that everything is working fine.

I will continue the game to find more possible problems.

**Comment by SwimmingTiger** [comment]
I found that I could draw a lot of makers by searching the quest "https://classic.wowhead.com/quest=1712/cyclonian" in the ClassicCodex Browser.

All icons are drawn in 1 second. Although it was obvious when drawing, there was no stuck in the follow-up. very good.

**Comment by SwimmingTiger** [comment]
In addition, I also noticed the lack of location data in the quest database. For example: https://classic.wowhead.com/quest=6621/king-of-the-foulweald does not have any location information about its quest item. At first I thought this was a bug in the addon. After searching in the database, it was discovered that there is no location data at all. But obviously, wowhead currently has the location data of the item.

Therefore, we should consider a comprehensive update of the database. Of course this has nothing to do with the current Pull Request. If I do the work, I will open a new Pull Request or Issue.

**Comment by pgarneau** [comment]
The database info was extracted from a private server database. There's no
way of extracting that data from wowhead. Questie started making manual
changes to their DB with the many devs they have and have recently offered
to possibly share the DB so we could benefit from updated data

**Comment by SwimmingTiger** [comment]
BigFoot users have reported a problem saying that after completing a class quest, they can still see its equivalent version appearing as an available quest in another zone, but they can't actually find the quest in game.

For example, someone finished https://classic.wowhead.com/quest=1505/veteran-uzzek so he cannot find https://classic.wowhead.com/quest=1818/speak-with-dillinger in game, but the latter is still displayed as an available quest on the map.

It seems that ClassicCodex (and pfQuest) is simply missing a quest mutual exclusion mechanism? @pgarneau

**Comment by Whaitiri** [comment]
Hey Swimming, im just a random person who likes this addon and wants to use it since it stopped working! I contacted the addon developer on reddit since I was having issues and it led me here. 

Another aspect of the performance issues, I believe, is the drawing of map markers for world drops, i.e. the quest Cyclonian has Liferoot as one of the required items, which has a very low chance to drop from many mobs in the game. This causes ClassicCodex to render map markers all over the world map for an extremely large number of mobs, and causes a lot of stuttering. While talking to the addon developer he suggested changing the `minimumDropChance` variable to equal `1` instead of `0`, which will hide Liferoot during Cyclonian and any similar quests (Nogg's Ring Redo has Moss Agate as a requirement, as another example off my head).

Just thought you'd like to bundle this in with your changes since it seems (tangentially) related. It's a one character change but here's a commit for reference: https://github.com/Whaitiri/ClassicCodex/commit/1f84bd9f0f2c55d0c4ec3d9b7544c7649d0648ed

**Comment by Whaitiri** [comment]
Thanks for your work on this addon either way, think I'll be using your version for a little while :)

**Comment by SwimmingTiger** [comment]
I have just pushed a minor fix for a big issue (4142bb5). For some quests (such as id 1149 `Test of Faith`), `GetQuestLogLeaderBoard()` may get a full `nil` returns. At this point the addon will continue to trigger Lua errors and will not be able to render any new map markers.

**Comment by SwimmingTiger** [comment]
@Whaitiri Thanks for your solution, I will add it as an option in ClassicCodex Settings.

**Comment by SwimmingTiger** [comment]
@pgarneau There are currently no more bug feedback. I think you can merge this Pull Request now.

The option of `minimumDropChance` will become another Pull Request.

**Comment by pgarneau** [comment]
Please modify the minimumDropChance at least 2-3% and you can dp a PR later
for an ingame option.

Ill merge after

**Comment by SwimmingTiger** [comment]
@pgarneau Done. Added a new option to hide low probability drop items. The default value is 2%, which only applies the item that from the QuestLog (browser queries are not restricted).

**Pull request merged**
